"""add migration

Revision ID: dcf175d68a1f
Revises: 791279dd0760
Create Date: 2023-12-20 01:17:42.122194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf175d68a1f'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholars_name'), 'scholars', ['name'], unique=False)
    op.drop_index('ix_students_name', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=55), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('birthday', sa.DATETIME(), nullable=True),
    sa.Column('enrolled_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_students_name', 'students', ['name'], unique=False)
    op.drop_index(op.f('ix_scholars_name'), table_name='scholars')
    op.drop_table('scholars')
    # ### end Alembic commands ###
